version: '3.8'

services:

  postgres:
    container_name: music-db
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '${DATABASE_PORT}:5432'

volumes:
  postgres: